import { useMemo, useState } from 'react';
const safeArray=v=>Array.isArray(v)?v:[];
const pct=v=>{const n=Number(v);return Number.isFinite(n)?Math.round(n<=1?n*100:n):0;};
const text=v=>String(v||'').trim();
const norm=v=>text(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const degreePattern=/\b(ph\.?d|doctor|master|m\.?s\.?|m\.?sc|mba|bachelor|b\.?s\.?|b\.?sc|associate|a\.?s\.?)\b/i;
const SkillDashboard=({results,onBack,onRecommendations})=>{
 const [activeTab,setActiveTab]=useState('resume'),[selectedSkill,setSelectedSkill]=useState(null);
 const skills=safeArray(results?.extracted_skills), explanations=safeArray(results?.explanations), rawEducation=safeArray(results?.education||results?.structured_evidence?.education), experience=safeArray(results?.experience||results?.structured_evidence?.experience), rawProjects=safeArray(results?.projects||results?.structured_evidence?.projects), publications=safeArray(results?.publications||results?.structured_evidence?.publications), credentials=safeArray(results?.certifications_from_resume||results?.structured_evidence?.certifications), rawCourses=safeArray(results?.courses_from_resume||results?.structured_evidence?.courses), years=Number(results?.total_experience_years??results?.structured_evidence?.total_experience_years??0);
 const formalEducation=useMemo(()=>rawEducation.filter(e=>degreePattern.test(`${text(e?.program_or_degree)} ${text(e?.field_of_study)}`)),[rawEducation]);
 const educationTraining=useMemo(()=>rawEducation.filter(e=>!formalEducation.includes(e)),[rawEducation,formalEducation]);
 const training=useMemo(()=>{const seen=new Set();return [...educationTraining,...rawCourses].filter(c=>{const k=norm(c?.program_or_degree||c?.name);if(!k||seen.has(k))return false;seen.add(k);return true;});},[educationTraining,rawCourses]);
 const professionalEvidence=useMemo(()=>{const tk=new Set(training.map(c=>norm(c?.program_or_degree||c?.name)));return credentials.filter(c=>!tk.has(norm(c?.name)));},[credentials,training]);
 const projectAccomplishments=useMemo(()=>{if(rawProjects.length)return rawProjects;const pat=/(project|commission|install|implement|design|startup|start-up|acceptance|integrat|upgrade|deploy|construct|dismantl|supervis|coordinate)/i,seen=new Set(),out=[];experience.forEach(r=>safeArray(r?.responsibilities).forEach(x=>{const v=text(x),k=norm(v);if(!v||!pat.test(v)||seen.has(k))return;seen.add(k);out.push({name:text(r?.role)?`${r.role} project accomplishment`:'Project accomplishment',description:v,employer:text(r?.employer)});}));return out.slice(0,8);},[rawProjects,experience]);
 const recommendations=useMemo(()=>[...safeArray(results?.recommendations)].sort((a,b)=>(Number(b.match_score)||0)-(Number(a.match_score)||0)),[results?.recommendations]),bestCareer=recommendations[0]||null;
 const categories=useMemo(()=>{const d={};skills.forEach(s=>{const c=s?.category||'Other';d[c]=(d[c]||0)+1;});return d;},[skills]);
 const summary=[['Skills',skills.length],['Formal education',formalEducation.length],['Training',training.length],['Work roles',experience.length],['Experience',years?`${years.toFixed(1)} yrs`:'0 yrs'],['Projects',projectAccomplishments.length],['Publications',publications.length]];
 const Card=({title,children})=><div className="rounded-2xl border border-slate-200 bg-white p-5"><h4 className="font-bold text-slate-900">{title}</h4><div className="mt-2 text-sm leading-6 text-slate-600">{children}</div></div>;
 const edu=(e,i)=><Card key={i} title={text(e.program_or_degree)||text(e.name)||'Education record'}><p>{text(e.institution)||text(e.institution_or_provider)||'Institution not detected'}</p>{text(e.field_of_study)&&<p>Field: {e.field_of_study}</p>}{text(e.end_or_expected_date)&&<p>Completed: {e.end_or_expected_date}</p>}</Card>;
 return <div className="overflow-hidden rounded-3xl border border-slate-200/80 bg-white shadow-[0_24px_70px_-30px_rgba(15,23,42,0.35)]">
 <div className="bg-slate-950 px-6 py-8 text-white md:px-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 inline-flex rounded-full border border-white/10 bg-white/10 px-3 py-1 text-xs font-semibold uppercase tracking-[.16em] text-cyan-200">Resume analysis complete</div><h1 className="text-3xl font-bold md:text-4xl">Review your resume evidence</h1><p className="mt-2 text-sm text-slate-300">Verify skills, formal education, completed training, work history, project accomplishments and publications before Career Intelligence.</p></div><button onClick={onBack} className="rounded-xl border border-white/15 bg-white/10 px-4 py-2.5 text-sm font-semibold">Analyze another document</button></div><div className="mt-7 grid gap-3 sm:grid-cols-3 lg:grid-cols-7">{summary.map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-white/10 p-4"><p className="text-xs uppercase text-slate-300">{l}</p><p className="mt-1 text-2xl font-bold">{v}</p></div>)}</div></div>
 <div className="border-b px-6 md:px-8"><div className="flex flex-wrap gap-2 py-3">{[['resume','Resume Evidence'],['skills','Skill Inventory'],['explanations','Skill Evidence'],['recommendations','Career Snapshot']].map(([t,l])=><button key={t} onClick={()=>setActiveTab(t)} className={`rounded-xl px-4 py-2 text-sm font-semibold ${activeTab===t?'bg-slate-950 text-white':'text-slate-600'}`}>{l}</button>)}</div></div>
 <div className="p-6 md:p-8">
 {activeTab==='resume'&&<div className="space-y-7"><div><h3 className="text-xl font-bold">Structured resume evidence</h3><p className="mt-1 text-sm text-slate-500">Formal degrees, completed training and professional evidence are kept separate so career scoring can use them appropriately.</p></div>
 <section><h3 className="font-bold">Formal education <span className="text-slate-400">({formalEducation.length})</span></h3><div className="mt-3 grid gap-3 md:grid-cols-2">{formalEducation.length?formalEducation.map(edu):<p className="text-sm text-amber-700">No formal degree records were detected.</p>}</div></section>
 <section><h3 className="font-bold">Completed training & courses <span className="text-slate-400">({training.length})</span></h3><div className="mt-3 grid gap-3 md:grid-cols-2">{training.length?training.map(edu):<p className="text-sm text-slate-500">No separate completed training records were detected.</p>}</div></section>
 <section><div className="flex flex-wrap items-center gap-3"><h3 className="font-bold">Work experience <span className="text-slate-400">({experience.length} roles)</span></h3><span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-semibold text-indigo-700">{years?`${years.toFixed(1)} total non-overlapping years`:'Experience duration not detected'}</span></div><div className="mt-3 grid gap-3 md:grid-cols-2">{experience.map((e,i)=><Card key={i} title={text(e.role)||'Work role'}><p>{text(e.employer)||'Employer not detected'}</p>{(e.start_date||e.end_date)&&<p>{text(e.start_date)} → {text(e.end_date)}</p>}{safeArray(e.responsibilities).length>0&&<p className="mt-2">{safeArray(e.responsibilities).slice(0,2).join(' ')}</p>}</Card>)}</div></section>
 <section><h3 className="font-bold">Project accomplishments <span className="text-slate-400">({projectAccomplishments.length})</span></h3><p className="mt-1 text-sm text-slate-500">Includes explicit projects and substantial project work described in employment history.</p><div className="mt-3 grid gap-3 md:grid-cols-2">{projectAccomplishments.map((p,i)=><Card key={i} title={text(p.name)||'Project accomplishment'}>{text(p.employer)&&<p className="mb-1 text-xs font-semibold uppercase text-slate-400">{p.employer}</p>}<p>{text(p.description)||text(p.evidence)}</p></Card>)}</div></section>
 <section><h3 className="font-bold">Publications <span className="text-slate-400">({publications.length})</span></h3><div className="mt-3 grid gap-3">{publications.map((p,i)=><Card key={i} title={text(p.title)||'Publication'}>{text(p.citation)||text(p.evidence)}</Card>)}</div></section>
 {professionalEvidence.length>0&&<section><h3 className="font-bold">Professional credentials, membership & recognition</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{professionalEvidence.map((c,i)=><Card key={i} title={text(c.name)||'Professional evidence'}>{text(c.provider)||text(c.evidence)}</Card>)}</div></section>}
 <div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><p className="font-bold text-indigo-950">Next: Career Intelligence</p><p className="mt-1 text-sm text-indigo-900">Career matching uses normalized competencies. Languages remain useful profile evidence but do not independently raise technical career readiness.</p>{bestCareer&&<button onClick={()=>onRecommendations(results)} className="mt-4 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white">Open Career Intelligence</button>}</div></div>}
 {activeTab==='skills'&&<div className="grid gap-6 xl:grid-cols-[.8fr_1.2fr]"><div className="rounded-2xl border bg-slate-50 p-5"><h3 className="font-bold">Skill distribution</h3><p className="mt-1 text-sm text-slate-500">All evidence-backed skills are preserved. Equivalent competencies are normalized only for career scoring, not deleted from your evidence.</p><div className="mt-5 space-y-4">{Object.entries(categories).map(([c,n])=><div key={c}><div className="flex justify-between text-sm"><span>{c}</span><span>{n}</span></div><div className="mt-1 h-2 rounded-full bg-slate-200"><div className="h-full rounded-full bg-indigo-600" style={{width:`${skills.length?n/skills.length*100:0}%`}}/></div></div>)}</div></div><div><h3 className="font-bold">Extracted skills</h3><p className="mt-1 text-sm text-slate-500">Confidence means how certain the extractor is that the evidence is present.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{skills.map((s,i)=><button key={i} onClick={()=>setSelectedSkill(s)} className="rounded-2xl border p-4 text-left"><div className="flex justify-between"><div><b>{s?.name||'Unnamed skill'}</b><p className="text-xs text-slate-500">{s?.category||'Other'}</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs text-emerald-700">{pct(s?.confidence)}%</span></div></button>)}</div></div>{selectedSkill&&<div className="xl:col-span-2 rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><b>{selectedSkill.name}</b><p className="mt-2 text-sm text-slate-700">{explanations.find(e=>e?.skill===selectedSkill.name)?.evidence||selectedSkill.evidence||'Evidence text not available.'}</p></div>}</div>}
 {activeTab==='explanations'&&<div className="grid gap-4 md:grid-cols-2">{explanations.map((e,i)=><div key={i} className="rounded-2xl border p-5"><b>{e?.skill||'Skill evidence'}</b><p className="mt-3 text-sm text-slate-600">{e?.reasoning}</p><div className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{e?.evidence||'Not available'}</div></div>)}</div>}
 {activeTab==='recommendations'&&<div className="space-y-5">{bestCareer&&<div className="rounded-2xl border border-indigo-100 bg-indigo-50 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Best current match</p><div className="mt-2 flex flex-wrap items-center gap-3"><h2 className="text-2xl font-bold">{bestCareer.path}</h2><span className="rounded-full bg-indigo-600 px-3 py-1 text-xs font-semibold text-white">{pct(bestCareer.match_score)}% readiness</span></div><p className="mt-2 text-sm text-slate-600">{bestCareer.match_reason}</p></div>}<div className="grid gap-4 lg:grid-cols-2">{recommendations.map((r,i)=><div key={r?.id||i} className="rounded-2xl border p-5"><p className="text-xs font-bold uppercase text-indigo-600">{i===0?'Best current match':r.category}</p><div className="flex justify-between"><h4 className="text-lg font-bold">{r.path}</h4><b>{pct(r.match_score)}%</b></div><p className="mt-3 text-sm text-slate-600">{r.match_reason}</p><p className="mt-3 text-xs text-slate-500">Core competencies evidenced: {safeArray(r.matched_skills).length} · Core gaps: {safeArray(r.missing_skills).length}</p></div>)}</div></div>}
 </div></div>;
};
export default SkillDashboard;
