"""Broader fallback career catalog for Skills Pathfinder.

This catalog expands the original engineering/data prototype into multiple
student fields. Salary/outlook strings are deliberately non-numeric where a
current authoritative market lookup has not yet been wired, avoiding stale or
invented figures. The future occupation layer should replace these placeholders
with BLS/O*NET-derived current data.
"""


def _career(
    career_id,
    path,
    category,
    required_skills,
    certifications=None,
    degrees=None,
    next_steps=None,
    resources=None,
    regulated=False,
):
    return {
        "id": career_id,
        "path": path,
        "category": category,
        "required_skills": required_skills,
        "job_outlook": "Current market lookup required",
        "median_salary": "Varies by location and experience",
        "top_locations": ["United States"],
        "recommended_certifications": certifications or [],
        "recommended_degrees": degrees or [],
        "next_steps": next_steps or [],
        "learning_resources": resources or [],
        "regulated_role": regulated,
    }


EXTENDED_CAREER_PATHS = [
    _career(
        "registered_nurse",
        "Registered Nurse",
        "Healthcare & Nursing",
        ["Patient Care", "Clinical Assessment", "Medication Administration", "Healthcare", "Registered Nurse License"],
        certifications=[{"name": "RN Licensure / NCLEX-RN", "provider": "State Board of Nursing / NCSBN", "time": "After approved nursing program", "cost": "Varies", "url": "https://www.nclex.com/"}],
        degrees=[{"name": "Associate or Bachelor of Science in Nursing", "type": "Nursing Degree", "duration": "2-4 years", "format": "On-campus/clinical"}],
        next_steps=["Complete an approved nursing program", "Meet state licensure requirements", "Prepare for and pass NCLEX-RN"],
        resources=[{"name": "NCSBN Nursing Licensure", "type": "Official", "cost": "Varies", "url": "https://www.ncsbn.org/"}],
        regulated=True,
    ),
    _career(
        "medical_assistant",
        "Medical Assistant",
        "Healthcare",
        ["Patient Care", "Vital Signs", "Medical Terminology", "Clinical Procedures", "Communication"],
        certifications=[{"name": "Certified Medical Assistant", "provider": "AAMA", "time": "Varies", "cost": "Varies", "url": "https://www.aama-ntl.org/"}],
        next_steps=["Strengthen clinical procedures and medical terminology", "Consider an accredited medical-assisting program"],
    ),
    _career(
        "healthcare_administrator",
        "Healthcare Administrator",
        "Healthcare Administration",
        ["Healthcare Administration", "Operations Management", "Communication", "Budget Management", "Compliance", "Leadership"],
        degrees=[{"name": "Healthcare Administration or Health Services Management", "type": "Bachelor/Master", "duration": "Varies", "format": "Online/On-campus"}],
        next_steps=["Build healthcare operations knowledge", "Develop compliance, budgeting, and leadership skills"],
    ),
    _career(
        "clinical_research_coordinator",
        "Clinical Research Coordinator",
        "Clinical Research",
        ["Clinical Research", "Research", "Data Collection", "Regulatory Compliance", "Communication", "Documentation"],
        certifications=[{"name": "Clinical Research Coordinator Certification", "provider": "ACRP/SOCRA", "time": "Eligibility varies", "cost": "Varies", "url": "https://acrpnet.org/"}],
        next_steps=["Learn clinical research regulations and Good Clinical Practice", "Gain research-site or laboratory experience"],
    ),
    _career(
        "public_health_specialist",
        "Public Health Specialist",
        "Public Health",
        ["Public Health", "Epidemiology", "Health Education", "Data Analysis", "Community Outreach", "Communication"],
        degrees=[{"name": "Master of Public Health", "type": "Graduate Degree", "duration": "1-2 years", "format": "Online/On-campus"}],
        next_steps=["Build epidemiology and population-health analysis skills", "Gain community or public-health program experience"],
    ),
    _career(
        "medical_lab_technologist",
        "Medical Laboratory Technologist",
        "Laboratory & Clinical Science",
        ["Laboratory Techniques", "Biology", "Chemistry", "Quality Control", "Laboratory Safety", "Clinical Laboratory"],
        certifications=[{"name": "Medical Laboratory Scientist Certification", "provider": "ASCP", "time": "Eligibility varies", "cost": "Varies", "url": "https://www.ascp.org/"}],
        next_steps=["Develop clinical laboratory competency", "Review certification and state licensure requirements"],
        regulated=True,
    ),
    _career(
        "biology_research_assistant",
        "Biology Research Assistant",
        "Science & Research",
        ["Biology", "Research", "Laboratory Techniques", "Data Analysis", "Scientific Writing", "Statistics"],
        next_steps=["Build laboratory/research experience", "Strengthen statistics and scientific communication"],
    ),
    _career(
        "environmental_scientist",
        "Environmental Scientist",
        "Environmental Science",
        ["Environmental Science", "Data Analysis", "GIS", "Research", "Field Sampling", "Environmental Compliance"],
        next_steps=["Develop field sampling and GIS skills", "Learn environmental regulations relevant to your target sector"],
    ),
    _career(
        "business_analyst",
        "Business Analyst",
        "Business & Analytics",
        ["Business Analysis", "Requirements Gathering", "Data Analysis", "Communication", "Process Improvement", "Excel"],
        certifications=[{"name": "ECBA", "provider": "IIBA", "time": "Varies", "cost": "Varies", "url": "https://www.iiba.org/"}],
        next_steps=["Practice requirements documentation", "Build process-mapping and stakeholder-analysis experience"],
    ),
    _career(
        "accountant",
        "Accountant",
        "Accounting & Finance",
        ["Accounting", "Financial Reporting", "Excel", "Bookkeeping", "General Ledger", "Tax"],
        certifications=[{"name": "Certified Public Accountant", "provider": "State Boards / NASBA", "time": "Eligibility varies", "cost": "Varies", "url": "https://nasba.org/"}],
        next_steps=["Strengthen accounting fundamentals and financial reporting", "Review CPA eligibility if public accounting is a target"],
    ),
    _career(
        "financial_analyst",
        "Financial Analyst",
        "Finance",
        ["Financial Analysis", "Excel", "Financial Modeling", "Accounting", "Data Analysis", "Forecasting"],
        certifications=[{"name": "CFA Program", "provider": "CFA Institute", "time": "Multi-level", "cost": "Varies", "url": "https://www.cfainstitute.org/"}],
        next_steps=["Build financial models", "Strengthen accounting, valuation, and forecasting skills"],
    ),
    _career(
        "human_resources_specialist",
        "Human Resources Specialist",
        "Human Resources",
        ["Human Resources", "Recruiting", "Employee Relations", "Communication", "HRIS", "Compliance"],
        certifications=[{"name": "SHRM-CP", "provider": "SHRM", "time": "Eligibility varies", "cost": "Varies", "url": "https://www.shrm.org/"}],
        next_steps=["Learn employment practices and HR systems", "Gain recruiting or employee-relations experience"],
    ),
    _career(
        "marketing_specialist",
        "Marketing Specialist",
        "Marketing",
        ["Marketing", "Digital Marketing", "Content Creation", "Analytics", "Communication", "Social Media"],
        next_steps=["Build a campaign portfolio", "Learn web/social analytics and conversion measurement"],
    ),
    _career(
        "administrative_coordinator",
        "Administrative Coordinator",
        "Administration",
        ["Administration", "Microsoft Office", "Scheduling", "Communication", "Document Management", "Customer Service"],
        next_steps=["Strengthen office systems, scheduling, and documentation", "Demonstrate organization and stakeholder support experience"],
    ),
    _career(
        "operations_manager",
        "Operations Manager",
        "Operations & Management",
        ["Operations Management", "Leadership", "Process Improvement", "Budget Management", "Project Management", "Problem Solving"],
        next_steps=["Build process-improvement and KPI management experience", "Strengthen budgeting and people leadership"],
    ),
    _career(
        "supply_chain_analyst",
        "Supply Chain Analyst",
        "Supply Chain & Logistics",
        ["Supply Chain", "Logistics", "Excel", "Data Analysis", "Inventory Management", "Forecasting"],
        next_steps=["Learn inventory and demand planning", "Build analytics projects using supply-chain data"],
    ),
    _career(
        "teacher",
        "Teacher",
        "Education",
        ["Teaching", "Lesson Planning", "Classroom Management", "Communication", "Assessment", "Curriculum Development"],
        next_steps=["Review state teacher-certification requirements", "Develop lesson planning and classroom-management evidence"],
        regulated=True,
    ),
    _career(
        "instructional_coordinator",
        "Instructional Coordinator",
        "Education Administration",
        ["Curriculum Development", "Instructional Design", "Teaching", "Assessment", "Leadership", "Data Analysis"],
        next_steps=["Build curriculum-design experience", "Strengthen educational data and teacher-support skills"],
    ),
    _career(
        "historian_archivist",
        "Historian / Archivist",
        "History & Humanities",
        ["History", "Research", "Archival Research", "Writing", "Source Analysis", "Documentation"],
        next_steps=["Build archival and primary-source research experience", "Develop a research/writing portfolio"],
    ),
    _career(
        "software_developer",
        "Software Developer",
        "Software & IT",
        ["Programming", "Python", "JavaScript", "Git", "Software Development", "Problem Solving"],
        next_steps=["Build deployable software projects", "Practice version control, testing, APIs, and data structures"],
    ),
    _career(
        "cybersecurity_analyst",
        "Cybersecurity Analyst",
        "Cybersecurity",
        ["Cybersecurity", "Network Security", "Security Monitoring", "Incident Response", "Linux", "Risk Management"],
        certifications=[{"name": "Security+", "provider": "CompTIA", "time": "Varies", "cost": "Varies", "url": "https://www.comptia.org/certifications/security"}],
        next_steps=["Build networking and security-monitoring fundamentals", "Practice incident-response and vulnerability-analysis labs"],
    ),
    _career(
        "cloud_support_engineer",
        "Cloud Support Engineer",
        "Cloud & Infrastructure",
        ["Cloud Computing", "AWS", "Azure", "Linux", "Networking", "Troubleshooting"],
        next_steps=["Build hands-on cloud labs", "Strengthen Linux, networking, identity, and troubleshooting"],
    ),
    _career(
        "data_scientist",
        "Data Scientist",
        "Data & AI",
        ["Python", "SQL", "Statistics", "Machine Learning", "Pandas", "Data Analysis"],
        next_steps=["Build end-to-end machine-learning projects", "Strengthen statistics, experimentation, and model evaluation"],
    ),
    _career(
        "machine_learning_engineer",
        "Machine Learning Engineer",
        "AI & Machine Learning",
        ["Python", "Machine Learning", "Deep Learning", "PyTorch", "TensorFlow", "Software Development"],
        next_steps=["Build deployable ML systems", "Learn model serving, evaluation, pipelines, and software engineering"],
    ),
    _career(
        "database_administrator",
        "Database Administrator",
        "Database & IT",
        ["SQL", "Database Administration", "PostgreSQL", "SQL Server", "Backup and Recovery", "Performance Tuning"],
        next_steps=["Practice backup/recovery and database security", "Develop performance-tuning and monitoring skills"],
    ),
    _career(
        "network_administrator",
        "Network Administrator",
        "Networking & IT",
        ["Networking", "TCP/IP", "Network Security", "Troubleshooting", "Cisco", "Windows Server"],
        certifications=[{"name": "CCNA", "provider": "Cisco", "time": "Varies", "cost": "Varies", "url": "https://www.cisco.com/site/us/en/learn/training-certifications/certifications/enterprise/ccna/index.html"}],
        next_steps=["Build routing, switching, and network-security labs", "Strengthen troubleshooting and systems administration"],
    ),
    _career(
        "civil_engineer",
        "Civil Engineer",
        "Engineering",
        ["Civil Engineering", "AutoCAD", "Structural Analysis", "Project Management", "Construction", "Engineering Design"],
        next_steps=["Build design/project evidence", "Review FE/PE licensing pathway where applicable"],
    ),
    _career(
        "mechanical_engineer",
        "Mechanical Engineer",
        "Engineering",
        ["Mechanical Engineering", "CAD", "Mechanical Design", "Thermodynamics", "Manufacturing", "Troubleshooting"],
        next_steps=["Build CAD/design projects", "Develop analysis, manufacturing, and testing experience"],
    ),
    _career(
        "project_manager",
        "Project Manager",
        "Project Management",
        ["Project Management", "Risk Management", "Stakeholder Management", "Scheduling", "Budget Management", "Communication"],
        certifications=[{"name": "Project Management Professional (PMP)", "provider": "PMI", "time": "Eligibility varies", "cost": "Varies", "url": "https://www.pmi.org/certifications/project-management-pmp"}],
        next_steps=["Document project outcomes and ownership", "Strengthen scheduling, risk, budget, and stakeholder-management evidence"],
    ),
]
